### PR TITLE
Change 'Web NFC API' to 'Web NFC' consistently

### PR DESCRIPTION
**Pull request by zolkis**
Continuing #404 
Signed-off-by: Zoltan Kis <zoltan.kis@intel.com>

***
<a href="https://pr-preview.s3.amazonaws.com/zolkis/web-nfc/pull/405.html" title="Last updated on Oct 23, 2019, 10:56 AM UTC (f412a43)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/web-nfc/405/66daf2f...zolkis:f412a43.html" title="Last updated on Oct 23, 2019, 10:56 AM UTC (f412a43)">Diff</a>

### CODE REVIEW

**Review by beaufortfrancois — APPROVED** [review]
LGTM

**Comment by beaufortfrancois** [comment]
Shall we update README.md as well?

**Comment by zolkis** [comment]
Right, I will do that now.

**Comment by zolkis** [comment]
Amended the previous commit but left the "API" there in one place, just to clarify it's an API spec.

**Review by beaufortfrancois — APPROVED** [review]
Still LGTM

**Comment by beaufortfrancois** [comment]
Can you change GitHub repo title as well?
image

**Comment by zolkis** [comment]
Anssi has changed the repo title.

**Pull request merged**
