### PR TITLE
New version of the Web NFC specification and the Security and Privacy document.

### LINKED ISSUE #4: Use wording from [powerful-features] to implement HTTPS restriction
_From @jyasskin on February 7, 2015 2:35_

https://w3c.github.io/webappsec/specs/powerfulfeatures/#new suggests putting wording in each algorithm that needs to be constrained to HTTPS.

_Copied from original issue: w3c/nfc#62_

### LINKED ISSUE #29: Say "in parallel" rather than "asynchronously"
The former is a defined term in HTML.

### LINKED ISSUE #34: Add "Sending data to NFC peers" example
The spec is clear on the [use cases](https://w3c.github.io/web-nfc/#use-cases) it aims to address. Currently, examples exists for reading and writing NFC tags, but an example for sending data to NFC peers is missing from [examples](https://w3c.github.io/web-nfc/#examples). It would be good to explain the key use cases in terms of example code. 

[Maintaining example code (as well as the use cases) as the API evolves allows people who don't read WebIDL (e.g. most web developers) to provide feedback. Also, example code helps find any developer ergonomics issues that may be masked by WebIDL.]

### LINKED ISSUE #45: Need ability to cancel a message push
When a pushMessage (formerly send) Promise is unresolved, do subsequent calls queue, replace, or are they rejected?

In any case, there needs to be a mechanism for cancelling a message push.

Also, what is the meaning of

> 10. If after making the request the connection is lost, reject promise with "TimeoutError"

in the [draft API](http://w3c.github.io/web-nfc/index.html#the-send-method)? Is this when data transfer is incomplete?

### PR DESCRIPTION
**Pull request by zolkis**
Algorithms extended and reworked.
Changed data representation. 
New security policies. 
Use watches instead of events. 
Fixed terminology related issues. 
Renamed send() to pushMessage().
Added timeout to push options. 
Issues addressed: #2, #3, #22, #26, #28, #30, #31, #32, #33, #35, #36, #38, #39, #40.
Also,
Fixed #4: use wording from [powerful features].
Fixed #29: use "in parallel" instead on "asynchronously".
Fixed #34: add example for sending data to NFC peer.
Fixed #45: add cancelPush() method.
Also, added steps on what happens with watches and push messages when focus is switched to another browsing context.

### CODE REVIEW

**Comment by mrj** [comment]
Should NFCDeviceType be changed to NFCPushTarget?

**Comment by zolkis** [comment]
We went back and forth between these two names. Perhaps NFCPushTarget is more correct.

**Comment by zolkis** [comment]
Will make a new commit in this PR to fix it.

**Comment by zolkis** [comment]
It seems that I have already done that and have already forgotten it :). Perhaps the comment referred to removed code (draft.idl).

**Comment by mrj** [comment]
Yes, sorry, I thought draft.idl was the latest because it has the latest modification date.

**Comment by anssiko** [comment]
See also the [HTML diff](http://services.w3.org/htmldiff?doc1=http%3A%2F%2Fw3c.github.io%2Fweb-nfc%2Freleases%2F20150824%2F&doc2=https%3A%2F%2Frawgit.com%2Fzolkis%2Fweb-nfc%2Fgh-pages%2Findex.html) to the [latest published version](http://w3c.github.io/web-nfc/releases/20150824/).

**Comment by kenchris** [comment]
ok lgtm

**Comment by anssiko** [comment]
Thank you @zolkis and @kenchris. This is a significant update that addresses the open issues. I will merge this now. Couple of comments that can be addressed later:
- In "The pushMessage algorithm", "NFCPushOptions dictionary", and "The watch() method" sections, _options_ is undefined. You want to "Let _options_ be ..."
- The pushMessage algorithm is rather long (by design). If parts of it could be factored out, that might help with readability. This is just an editorial comment, however.

**Comment by zolkis** [comment]
> options is undefined. You want to "Let options be ..."

I thought formal parameters from the IDL don't need steps to explain their name binding.

> The pushMessage algorithm is rather long (by design)

Since often the algorithm is terminated in the sub-steps, it would be cumbersome to break it out to sub-algorithms, since then it's not clear what is meta-parameter and return values and what really belongs to the algorithm. I tried that slicing e.g. with the security steps, but it became a mess.

**Pull request merged**
