### PR TITLE
Move serialNumber from NDEFMessage to NFCReadingEvent, fixes #224

### LINKED ISSUE #224: Should we ignore NDEFMessage.serialNumber for NFCWriter::push()?
An attribute |serialNumber| has been added to NDEFMessage dictionary, and it seems only meaningful to NFCReadingEvent.
According to the [the push method in Spec](https://w3c.github.io/web-nfc/#the-push-method),  |serialNumber| in NDEFMessage passed to NFCWriter::push() will be ignored. Should we make a clear statement about this?

### PR DESCRIPTION
**Pull request by DonnaWuDongxia**

### CODE REVIEW

**Comment by DonnaWuDongxia** [comment]
@zolkis would you please take a look at this?

**Comment by zolkis** [comment]
Looks good.

**Comment by zolkis** [comment]
@kenchris are you ok with this change? Rationale is in #224

**Review by kenchris — APPROVED** [review]

**Comment by DonnaWuDongxia** [comment]
Thank you all! The [CL](https://chromium-review.googlesource.com/c/chromium/src/+/1655092) adding ReadingEvent will be updated accordingly soon .

**Pull request merged**
