### PR TITLE
Now that we use event listeners for watches, remove AbortSignal

### PR DESCRIPTION
**Pull request by kenchris**

### CODE REVIEW

**Review by littledan — COMMENTED** [review]
I don't see any logic to remove the watch when the EventListener is removed. Probably that should be added.

**Comment by kenchris** [comment]
The watch method will be removed soon at it will all depend on add / removing event listeners like @reillyeon suggested (same as geolocation spec)

**Review by littledan — APPROVED** [review]
OK, the change looks good as long as the logic is added back in a follow-on patch

**Comment by kenchris** [comment]
Sure, will do that.

**Pull request merged**
