### PR TITLE
Fix ReSpec warnings

### PR DESCRIPTION
**Pull request by alexshalamov**
This PR fixes ReSpec warnings. Improves cross-referencing within the spec as well as with external sources. It would be also easier to convert spec without warnings to bikeshed when needed.

### CODE REVIEW

**Comment by alexshalamov** [comment]
@kenchris @zolkis please take a look.

**Comment by zolkis** [comment]
LGTM. Thanks.

**Comment by alexshalamov** [comment]
Rebased to gh-pages

**Comment by alexshalamov** [comment]
@kenchris Do you have comments for this PR?

**Comment by anssiko** [comment]
Drive-by LGTM.

**Pull request merged**
