### PR TITLE
Add a bit more clarification about local type

### PR DESCRIPTION
**Pull request by kenchris**
@beaufortfrancois

***

### :boom: Error: 500 Internal Server Error :boom: ###

[PR Preview](https://github.com/tobie/pr-preview#pr-preview) failed to build. _(Last tried on Oct 24, 2019, 10:13 AM UTC)_.

<details>
<summary>More</summary>

PR Preview relies on a number of web services to run. There seems to be an issue with the following one:

:rotating_light: [Spec Generator](https://www.w3.org/2015/labs/) - Spec Generator is the web service used to build specs that rely on ReSpec.

:link: [Related URL](https://labs.w3.org/spec-generator/?type=respec&url=https%3A%2F%2Frawcdn.githack.com%2Fw3c%2Fweb-nfc%2F98e3868486c551f5e68c44153695147252e8cff9%2Findex.html%3FisPreview%3Dtrue)

```
Navigation Timeout Exceeded: 30000ms exceeded
```

_If you don't have enough information above to solve the error by yourself (or to understand to which web service the error is related to, if any), please [file an issue](https://github.com/tobie/pr-preview/issues/new?title=Error%20not%20surfaced%20properly&body=See%20w3c/web-nfc%23411.)._
</details>

### CODE REVIEW

**Comment by beaufortfrancois** [comment]
Can we explain why local types are actually a thing?

> Local Types are used whenever the burden of using a long, domain name-based External Type is too much, and there is no need to define its meaning outside of the local context.

**Comment by kenchris** [comment]
> Can we explain why local types are actually a thing?

They have very little overhead. Two bytes (header plus type name length) plus the size of the type name. As the record knows exactly what they represent, no need to store mime type and the like - just store the data.

Maybe you have better ways of explaining it :)

**Review by zolkis — APPROVED** [review]

**Comment by beaufortfrancois** [comment]
The way I understand it (and I may be wrong) is that local types are meant to avoid repeating the base record type. See example below

before 
```js
const writer = new NDEFWriter();
writer.push({ records: [
  {
    recordType: "example.com:shoppingItem",
    data: { records: [
      {
        recordType: "example.com:shoppingItemUrl",
        data: new TextEncoder('').encoder('https://example.com/123')
      },
      {
        recordType: "example.com:shoppingItemName",
        data: new TextEncoder('').encoder('NFC Tag')
      },
      {
        recordType: "example.com:shoppingItemDescription",
        data: new TextEncoder('').encoder('Pretty cool')
      },
  }
]});
```

after


```js
const writer = new NDEFWriter();
writer.push({ records: [
  {
    recordType: "example.com:shoppingItem",
    data: { records: [
      {
        recordType: "u",
        data: new TextEncoder('').encoder('https://example.com/123')
      },
      {
        recordType: "n",
        data: new TextEncoder('').encoder('NFC Tag')
      },
      {
        recordType: "d",
        data: new TextEncoder('').encoder('Pretty cool')
      },
  }
]});
```

**Comment by kenchris** [comment]
Yes that is what I mean with not needing namespacing

**Comment by zolkis** [comment]
It's well visible in the NDEF standard that local types are an afterthought, and not event the "context" is well defined, so we _assume_ another record, because that's how NFC Forum used them in Smart Poster. 

Whatever the thing is, there is a mechanism to use local typing and it may be useful for apps (even though I'd think those apps would choose another tech if they wanted to encapsulate their own doings).

**Comment by kenchris** [comment]
It does state
> Local Types are available for use within the context of another record

context == another record

**Comment by zolkis** [comment]
Then it talks (normatively) about application context that is not well defined. 
However, it does state the intention on saving on potentially long domain-name external types.

**Comment by beaufortfrancois** [comment]
Shall we update local type section with the intention then?

**Comment by kenchris** [comment]
Feel free to attempt and I will review :-)

**Pull request merged**
