### PR TITLE
Create .pr-preview.json

### PR DESCRIPTION
**Pull request by marcoscaceres**
Enable previews... someone might need to add pr-preview as an app to this repository.

### CODE REVIEW

**Comment by marcoscaceres** [comment]
@kenchris did you mange to enable the app in the settings?

**Comment by kenchris** [comment]
I don't see settings :-( I guess it is disabled for me

**Comment by marcoscaceres** [comment]
@siusin, sorry to bother you, but could you please enable the pr-preview application for this repo?

**Comment by marcoscaceres** [comment]
@siusin, sorry, never mind. It's working now.

**Pull request merged**
